# Usa una imagen base oficial de Node.js
FROM node:20.17.0-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /users/app

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY . .

# Expone el puerto en el que corre tu app
EXPOSE 3000

# Comando por defecto para correr la aplicación
CMD ["npm", "start"]
